### ISSUE TITLE
Error reading yaml file for postprocessing in deepcell

### ISSUE THREAD

**Issue by retogerber** [BodenmillerGroup/steinbock#101]
Hi

I encountered an error when specifying a yaml file for postprocessing in `steinbock segment deepcell`. If I run `steinbock segment deepcell --postprocess mesmer_postprocess.yml` I get the following error:

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/app/steinbock/steinbock/__main__.py", line 5, in <module>
    steinbock_cmd_group(prog_name="steinbock")
  File "/opt/venv/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/opt/venv/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/opt/venv/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/venv/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/venv/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/venv/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/app/steinbock/steinbock/segmentation/_cli/deepcell.py", line 164, in deepcell_cmd
    postprocess_kwargs = yaml.load(f)
TypeError: load() missing 1 required positional argument: 'Loader'
```
Seems to be probably because pyyaml v.6.0 now "always require `Loader` arg to `yaml.load()`" (see [here](https://github.com/yaml/pyyaml/blob/master/CHANGES)).

Thanks

Reto

**Comment by jwindhager** [comment]
Thanks for spotting this, @retogerber, I'll release a fix asap!
