### ISSUE TITLE
Error: Invalid value for '--pipe': File 'cell_measurement.cppipe' does not exist.

### ISSUE THREAD

**Issue by nilseling** [BodenmillerGroup/steinbock#102]
When calling 

```
steinbock measure cellprofiler prepare --masks masks_ilastik
steinbock measure cellprofiler run
```

`steinbock` throws following error:

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/app/steinbock/steinbock/__main__.py", line 5, in <module>
    steinbock_cmd_group(prog_name="steinbock")
  File "/opt/venv/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/opt/venv/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/opt/venv/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/venv/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/venv/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/venv/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/venv/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/app/steinbock/steinbock/measurement/_cli/cellprofiler.py", line 74, in prepare_cmd
    mask_files = io.list_mask_files(mask_dir, base_files=img_files)
  File "/app/steinbock/steinbock/io.py", line 214, in list_mask_files
    return _list_related_files(base_files, mask_dir, ".tiff")
  File "/app/steinbock/steinbock/io.py", line 62, in _list_related_files
    raise FileNotFoundError(related_file)
FileNotFoundError: masks_ilastik/Patient1_001.tiff
Usage: steinbock measure cellprofiler run [OPTIONS]
Try 'steinbock measure cellprofiler run --help' for help.

Error: Invalid value for '--pipe': File 'cell_measurement.cppipe' does not exist.
```

Using `steinbock` v0.13.3

**Comment by jwindhager** [comment]
And `steinbock measure cellprofiler prepare --masks masks_ilastik` does not show any error message or output?

**Comment by jwindhager** [comment]
Looks like you execute both commands in one go, could that be?

Output of `steinbock measure cellprofiler prepare --masks masks_ilastik`:
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/app/steinbock/steinbock/__main__.py", line 5, in <module>
    steinbock_cmd_group(prog_name="steinbock")
  File "/opt/venv/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/opt/venv/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/opt/venv/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/venv/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/venv/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/venv/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/venv/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/app/steinbock/steinbock/measurement/_cli/cellprofiler.py", line 74, in prepare_cmd
    mask_files = io.list_mask_files(mask_dir, base_files=img_files)
  File "/app/steinbock/steinbock/io.py", line 214, in list_mask_files
    return _list_related_files(base_files, mask_dir, ".tiff")
  File "/app/steinbock/steinbock/io.py", line 62, in _list_related_files
    raise FileNotFoundError(related_file)
FileNotFoundError: masks_ilastik/Patient1_001.tiff
```

Output `steinbock measure cellprofiler run`:
```
Usage: steinbock measure cellprofiler run [OPTIONS]
Try 'steinbock measure cellprofiler run --help' for help.

Error: Invalid value for '--pipe': File 'cell_measurement.cppipe' does not exist.
```

The latter error message makes sense, given that the `prepare` command failed.
