### ISSUE TITLE
calling cellprofiler app fails in 0.13.4

### ISSUE THREAD

**Issue by SchulzDan** [BodenmillerGroup/steinbock#105]
steinbock apps cellprofiler
Traceback (most recent call last):
  File "/opt/venv/bin/cellprofiler", line 5, in <module>
    from cellprofiler.__main__ import main
  File "/opt/venv/lib/python3.8/site-packages/cellprofiler/__main__.py", line 13, in <module>
    import bioformats.formatreader
  File "/opt/venv/lib/python3.8/site-packages/bioformats/__init__.py", line 21, in <module>
    import javabridge
  File "/opt/venv/lib/python3.8/site-packages/javabridge/__init__.py", line 38, in <module>
    from .jutil import start_vm, kill_vm, vm, activate_awt, deactivate_awt
  File "/opt/venv/lib/python3.8/site-packages/javabridge/jutil.py", line 162, in <module>
    import javabridge._javabridge as _javabridge
  File "_javabridge.pyx", line 1, in init _javabridge
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 80 from PyObject

**Comment by jwindhager** [comment]
Sorry for this, fixed with v0.13.5 [currently building](https://github.com/BodenmillerGroup/steinbock/actions/runs/1876902361) @SchulzDan
