### ISSUE TITLE
Error in "steinbock export histocat"

### ISSUE THREAD

**Issue by jparkinson375** [BodenmillerGroup/steinbock#136]
Hi All,

I am having an issue when I run the command to export a histoCAT folder from the Steinbock pipeline. The whole pipeline runs fine apart from this section as far as I can tell.

This is the traceback

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/app/steinbock/steinbock/__main__.py", line 17, in <module>
    steinbock_cmd_group(prog_name="steinbock")
  File "/opt/venv/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/venv/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/venv/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/venv/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/venv/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/venv/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/app/steinbock/steinbock/_cli/utils.py", line 35, in wrapper
    return func(*args, **kwargs)
  File "/app/steinbock/steinbock/export/_cli/_cli.py", line 142, in histocat_cmd
    histocat_mask = io._to_dtype(mask, np.uint16)[
  File "/app/steinbock/steinbock/io.py", line 36, in _to_dtype
    if src.dtype == dst_dtype:
AttributeError: 'NoneType' object has no attribute 'dtype'

I have tried removing the mask folder and then the command runs completely fine, so it seems to an issue specifically with the mask files.

Most likely I have just done something stupid when running the analysis, but any help would be much appreciated.

Thank you.

**Comment by jwindhager** [comment]
Hi @jparkinson375, thanks for reporting! This definitely looks like a bug. Will verify/fix in August (currently traveling).

**Comment by jparkinson375** [comment]
Just to update this, this has been fixed for me in the latest release.

Great work, thank you.
