### ISSUE TITLE
IMC recovery from txt file is potentially broken

### ISSUE THREAD

**Issue by jwindhager** [BodenmillerGroup/steinbock#150]
```
ERROR steinbock.preprocessing.imc - Error reading file raw/20220819_MC_NSCLCTcellexh_87C_1/20220819_MC_NSCLCTcellexh_87C_1/20220819_MC_NSCLC_Tcellexh_87C_1.mcd: sequence item 0: expected str instance, PosixPath found
Traceback (most recent call last):
  File "/app/steinbock/steinbock/preprocessing/imc.py", line 341, in _try_preprocess_mcd_images_from_disk
    recovery_txt_file = _match_txt_file(
  File "/app/steinbock/steinbock/preprocessing/imc.py", line 300, in _match_txt_file
    ", ".join(filtered_txt_files),
TypeError: sequence item 0: expected str instance, PosixPath found
```

@MureziCapaul

**Comment by jwindhager** [comment]
Closed with 56d0fe3f5e34ea8dd5f638abb7febe773742a33f
