### ISSUE TITLE
Deepcell command not found

### ISSUE THREAD

**Issue by sshin48** [BodenmillerGroup/steinbock#154]
deepcell command is not found for the most updated steinbock package (0.15.0)

**Comment by jwindhager** [comment]
Hi @sshin48, could you please elaborate how you installed steinbock? Thanks

**Comment by sshin48** [comment]
Hi @jwindhager, I downloaded steinbock through pips as I have been having issues with docker

**Comment by jwindhager** [comment]
I see, then probably the deepcell dependency isn't installed. Did you follow https://bodenmillergroup.github.io/steinbock/latest/install-python/ (box "package version conflicts")?

**Comment by sshin48** [comment]
Yes, I've tried both independently
# pip install --upgrade -r requirements_deepcell.txt
# pip install --upgrade -r requirements_deepcell-gpu.txt

**Comment by sshin48** [comment]
I tried running it again, this time this error comes up once I install w/o dependencies for steinbock[all] and deepcell, then input "steinbock --help":

Traceback (most recent call last):
  File "C:\Users\sshin48\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\sshin48\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\sshin48\AppData\Local\Programs\Python\Python39\Scripts\steinbock.exe\__main__.py", line 4, in <module>
  File "C:\Users\sshin48\AppData\Local\Programs\Python\Python39\lib\site-packages\steinbock\_cli\__init__.py", line 1, in <module>
    from ._cli import steinbock_cmd_group
  File "C:\Users\sshin48\AppData\Local\Programs\Python\Python39\lib\site-packages\steinbock\_cli\_cli.py", line 7, in <module>
    from ..preprocessing._cli import preprocess_cmd_group
  File "C:\Users\sshin48\AppData\Local\Programs\Python\Python39\lib\site-packages\steinbock\preprocessing\_cli\__init__.py", line 1, in <module>
    from ._cli import preprocess_cmd_group
  File "C:\Users\sshin48\AppData\Local\Programs\Python\Python39\lib\site-packages\steinbock\preprocessing\_cli\_cli.py", line 5, in <module>
    from .imc import imc_cli_available, imc_cmd_group
  File "C:\Users\sshin48\AppData\Local\Programs\Python\Python39\lib\site-packages\steinbock\preprocessing\_cli\imc.py", line 16, in <module>
    from .. import imc
  File "C:\Users\sshin48\AppData\Local\Programs\Python\Python39\lib\site-packages\steinbock\preprocessing\imc.py", line 222, in <module>
    acquisition: Optional[Acquisition],
NameError: name 'Acquisition' is not defined

**Comment by jwindhager** [comment]
Sorry, but I really cannot reproduce this error, starting from a fresh conda environment:

```
❯ conda create -n test python=3.8
...
❯ conda activate test
...
❯ pip install --upgrade -r requirements_deepcell.txt
...
❯ pip install --no-deps deepcell==0.12.3
...
❯ pip install --upgrade -r requirements.txt
...
❯ pip install --no-deps "steinbock[all]"
...
❯ steinbock --help
Usage: steinbock [OPTIONS] COMMAND [ARGS]...

Options:
  --version  Show the version and exit.
  --help     Show this message and exit.

Commands:
  preprocess  Extract and preprocess images from raw data
  classify    Perform pixel classification to extract probabilities
  segment     Perform image segmentation to create object masks
  measure     Extract object data from segmented images
  export      Export data to third-party formats
  utils       Various utilities and tools
  apps        Third-party applications
```

Are you sure you precisely followed the steps in the documentation, without installing any additional packages etc?
