### ISSUE TITLE
Image extraction from broken files

### ISSUE THREAD

**Issue by jwindhager** [BodenmillerGroup/steinbock#52]
As reported by @SchulzDan, image extraction from some broken txt/mcd files failed with the following error:

```
dan@dschulz:~$ steinbock preprocess imc images --hpf 50
img/20210915_ZTMA256_exhaustion_stain_DS_17.tiff
img/20210915_ZTMA256_exhaustion_stain_DS_18.tiff
img/20210915_ZTMA256_exhaustion_stain_DS_19.tiff
img/20210915_ZTMA256_exhaustion_stain_DS_20.tiff
img/20210915_ZTMA256_exhaustion_stain_DS_21.tiff
img/20210915_ZTMA256_exhaustion_stain_DS_22.tiff
img/20210915_ZTMA256_exhaustion_stain_DS_23.tiff
img/20210915_ZTMA256_exhaustion_stain_DS_24.tiff
img/20210915_ZTMA256_exhaustion_stain_DS_25.tiff
img/20210915_ZTMA256_exhaustion_stain_DS_26.tiff
img/20210915_ZTMA256_exhaustion_stain_DS_27.tiff
img/20210915_ZTMA256_exhaustion_stain_DS_28.tiff
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in run_module_as_main
    return run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/app/steinbock/steinbock/__main.py", line 5, in <module>
    steinbock_cmd_group(prog_name="steinbock")
  File "/opt/venv/lib/python3.8/site-packages/click/core.py", line 1137, in call
    return self.main(args, kwargs)
  File "/opt/venv/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/opt/venv/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/venv/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/venv/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/venv/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, ctx.params)
  File "/opt/venv/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(args, kwargs)
  File "/app/steinbock/steinbock/_env.py", line 90, in check_steinbock_version_wrapper
    return func(*args, kwargs)
  File "/app/steinbock/steinbock/preprocessing/cli/imc.py", line 182, in images_cmd
    for (
  File "/app/steinbock/steinbock/preprocessing/imc.py", line 213, in preprocess_images_from_disk
    with TxtParser(txt_file) as txt_parser:
  File "/opt/venv/lib/python3.8/site-packages/imctools/io/txt/txtparser.py", line 27, in _init
    self.acquisition_data = self.parse_acquisition(filepath)
  File "/opt/venv/lib/python3.8/site-packages/imctools/io/txt/txtparser.py", line 42, in _parse_acquisition
    long_data, channel_names, channel_labels = TxtParser._parse_csv(filepath)
  File "/opt/venv/lib/python3.8/site-packages/imctools/io/txt/txtparser.py", line 103, in _parse_csv
    header_cols = pd.read_csv(filepath, sep="\t", nrows=0).columns
  File "/opt/venv/lib/python3.8/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(args, *kwargs)
  File "/opt/venv/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/opt/venv/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/opt/venv/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 811, in __init
    self.engine = self.make_engine(self.engine)
  File "/opt/venv/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mappingengine  # type: ignore[call-arg]
  File "/opt/venv/lib/python3.8/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 69, in __init
    self.reader = parsers.TextReader(self.handles.handle, **kwds)
  File "pandas/libs/parsers.pyx", line 542, in pandas._libs.parsers.TextReader.__cinit
  File "pandas/_libs/parsers.pyx", line 642, in pandas._libs.parsers.TextReader._get_header
  File "pandas/_libs/parsers.pyx", line 843, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1917, in pandas._libs.parsers.raise_parser_error
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
```

Check:
- Can the files be repaired somehow?
- Is the information recovery strategy (txt for mcd) working as expected?
- Can the console output be improved?

Copies of broken files have been requested.

**Comment by jwindhager** [comment]
Verified. This originates from the specific local setup, which adds a file called `_____.txt` to the raw data directory/zip file. To not implement setup-specific exceptions, the suggested path forward is to just "clean up" the error message (specifically, to include the affected file name).
