### ISSUE TITLE
steinbock 0.10: cannot import 'register_translation' from 'skimage.feature'

### ISSUE THREAD

**Issue by ndamond** [BodenmillerGroup/steinbock#81]
Hi Jonas,
I get the error message below when trying to segment my images with steinbock 0.10.1 (command: `steinbock segment deepcell --minmax` on ubuntu 18.04). The command worked on the same dataset with steinbock 0.9.1 (with the same initial tensorflow warning).
Do you know how this can be fixed?
Thanks,
Nicolas
```
        WARNING:tensorflow:SavedModel saved prior to TF 2.5 detected when loading Keras model. Please ensure that you are saving the model with model.save() or tf.keras.models.save_model(), *NOT* tf.saved_model.save(). To confirm, there should be a file named "keras_metadata.pb" in the SavedModel directory.
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/app/steinbock/steinbock/__main__.py", line 5, in <module>
    steinbock_cmd_group(prog_name="steinbock")
  File "/opt/venv/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/opt/venv/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/opt/venv/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/venv/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/venv/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/venv/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/app/steinbock/steinbock/_env.py", line 90, in check_steinbock_version_wrapper
    return func(*args, **kwargs)
  File "/app/steinbock/steinbock/segmentation/_cli/deepcell.py", line 163, in deepcell_cmd
    for img_file, mask in deepcell.try_segment_objects(
  File "/app/steinbock/steinbock/segmentation/deepcell.py", line 81, in try_segment_objects
    app, predict = application.value(model=model)
  File "/app/steinbock/steinbock/segmentation/deepcell.py", line 33, in _mesmer_application
    from deepcell.applications import Mesmer
  File "/opt/venv/lib/python3.8/site-packages/deepcell/__init__.py", line 34, in <module>
    from deepcell import applications
  File "/opt/venv/lib/python3.8/site-packages/deepcell/applications/__init__.py", line 32, in <module>
    from deepcell.applications.application import Application
  File "/opt/venv/lib/python3.8/site-packages/deepcell/applications/application.py", line 37, in <module>
    from deepcell_toolbox.utils import resize, tile_image, untile_image
  File "/opt/venv/lib/python3.8/site-packages/deepcell_toolbox/__init__.py", line 30, in <module>
    from deepcell_toolbox import processing
  File "/opt/venv/lib/python3.8/site-packages/deepcell_toolbox/processing.py", line 37, in <module>
    from skimage.feature import peak_local_max, register_translation
ImportError: cannot import name 'register_translation' from 'skimage.feature' (/opt/venv/lib/python3.8/site-packages/skimage/feature/__init__.py)
```

**Comment by jwindhager** [comment]
Hi Nicolas, thanks for filing this! This is a bug and I'll release a fix asap, tomorrow the latest. Until then, version 0.10.0 should work. Sorry for this!

**Comment by jwindhager** [comment]
Fixed with https://github.com/BodenmillerGroup/steinbock/commit/94070453b2318faf02418e3ab9b636cce327bec2, version 0.10.2 is currently being built and released: https://github.com/BodenmillerGroup/steinbock/actions/runs/1550898968
